# This is a basic workflow to help you get started with Actions

name: Validate Katacoda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - id: checkout-code
      uses: actions/checkout@v2
    
    - id: install-katacoda-cli
      name: Install Katacoda CLI
      run: |
        sudo npm install katacoda-cli --global
    
    - id: validate-config
      name: Validate Katacoda Scenarios
      run: |
        katacoda validate:all --repo ${{ github.workspace }}
    
    - id: validate-markdown
      name: Validate Katacoda Markdown
      run: |
        sudo gem install mdl
        mdl ${{ github.workspace }}
